# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC

ACTION = 'action'
AUTH_TOKEN = 'auth_token'
COMPLETE = 'complete'
DATA = 'data'
DURATION = 'duration'
ENDTIME = 'endtime'
JOB_STATUS_REQUEST = 'job_status_request'
LANGUAGE = 'language'
OPERATION = 'operation'
PATH = 'path'
PERCENT_COMPLETE = 'percentComplete'
POLLING_INTERVAL = 'recommendedPollingInterval'
PROGRESS = 'progress'
REGION = 'region'
REQUEST_DATA = 'request_data'
REQUEST_ID = 'request_id'
REQUEST_PARAMETERS = 'request_parameters'
STARTTIME = 'starttime'
STATUS = 'status'
STATUS_ERROR = 'error'
STATUS_INPROGRESS = 'inprogress'
STATUS_NOT_FOUND = 'not_found'
STATUS_WARNING = 'warning'
TARGET = 'target'
TENANT_ID = 'tenant_id'
TXN_ID = 'txn_id'
VERSION = 'api_version'
USER_AGENT = "Operations Console"
